label: Sisu
description: 'Otsi ja halda lehe sisu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: Pealkiri
        type:
          label: 'Sisu t端端p'
        status:
          label: Staatus
          settings:
            format_custom_true: Avaldatud
        changed:
          label: Uuendati
      filters:
        title:
          expose:
            label: Pealkiri
        type:
          expose:
            label: 'Sisu t端端p'
        status:
          expose:
            label: Staatus
          group_info:
            group_items:
              1:
                title: Avaldatud
        langcode:
          expose:
            label: Keel
      title: Sisu
      empty:
        area_text_custom:
          content: 'Sisu puudub.'
  page_1:
    display_options:
      menu:
        title: Sisu
      tab_options:
        title: Sisu
        description: 'Otsi ja halda sisu'
