display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: TÃ¼hista
      fields:
        status:
          label: Staatus
          settings:
            format_custom_true: Avaldatud
        changed:
          label: Uuendati
      filters:
        status:
          group_info:
            group_items:
              1:
                title: Avaldatud
        langcode:
          expose:
            label: Keel
