label: 'Kohandatud plokkide teek'
description: 'Otsi ja halda kohandatud plokke.'
display:
  default:
    display_options:
      fields:
        info:
          label: 'Ploki kirjeldus'
        type:
          label: 'Ploki t端端p'
      filters:
        info:
          expose:
            label: 'Ploki kirjeldus'
        type:
          expose:
            label: 'Ploki t端端p'
      title: 'Kohandatud plokkide teek'
      empty:
        area_text_custom:
          content: 'Kohandatud plokke pole saadaval.'
  page_1:
    display_options:
      menu:
        title: 'Kohandatud plokkide teek'
