label: 'Uued kasutajad'
description: 'NÃ¤itab nimekirja viimati loodud kasutajakontodest.'
display:
  default:
    display_options:
      title: 'Uued kasutajad'
  block_1:
    display_title: 'Uued kasutajad'
    display_options:
      display_description: 'Uute kasutajate nimekiri'
      block_description: 'Uued kasutajad'
      block_category: Kasutaja
