description: 'Viimased logiteated'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        nothing:
          admin_label: Ikoon
        severity:
          label: Tõsidus
        timestamp:
          label: Date
        message:
          label: Teade
        name:
          label: Kasutaja
      filters:
        severity:
          expose:
            label: Tõsidus
      title: 'Viimased logiteated'
      empty:
        area:
          admin_label: 'Logis ei ole teateid.'
          content: 'Logis ei ole teateid.'
