harno_settings.admin_index:
  path: '/admin/config/veebiplatvorm'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Veebiplatvorm'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.settings_form:
  path: '/admin/config/veebiplatvorm/uldised-seaded'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoSettingsForm'
    _title: 'Veebiplatvormi Ã¼ldised seaded'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
harno_settings.colors_form:
  path: '/admin/config/veebiplatvorm/kujundus'
  defaults:
    _form: '\Drupal\harno_settings\Form\HarnoColorsForm'
    _title: 'Veebiplatvormi kujundus'
  requirements:
    _permission: 'administer harno settings'
  options:
    _admin_route: TRUE
